name: Build and Release

on: release

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Fabric artifacts
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #modrinth-id: aaaaaaaa # TODO: for automatic publishing, set your project's modrinth id here and add a repository secret named MODRINTH_TOKEN
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          #curseforge-id: 1111111 # TODO: set your project's curseforge id here and add a repository secret named CURSEFORGE_TOKEN if you want to enable publishing to cf
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }} # GitHub token is provided by GH automatically

          files: build/libs/!(*-@(dev|sources|all)).jar

      - name: Upload Forge artifacts
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #modrinth-id: aaaaaaaa # TODO: add modrinth/curseforge ids here too
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          #curseforge-id: 1111111
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs_forge/!(*-@(dev|sources|all)).jar
